CREATE TABLE IF NOT EXISTS historique_images (
  id INT NOT NULL AUTO_INCREMENT,
  image VARCHAR(255) NOT NULL,
  alt VARCHAR(255) DEFAULT NULL,
  ordre INT DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;